version: '3'
networks:
  main:
    driver: bridge

services:
  go_gw:
    build:
      context: ./go
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"

    image: ctrace-demo-go
    networks:
      - main
    ports:
      - "8004:80"
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      SERVICENAME: "go_gw"
    volumes:
      - ctrace-demo-logs:/var/log/

  go_hello:
    build:
      context: ./go
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"

    image: ctrace-demo-go
    networks:
      - main
    ports:
      - "8005:80"
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      SERVICENAME: "go_hello"

  js_gw:
    build:
      context: ./js
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"

    image: ctrace-demo-js
    networks:
      - main
    ports:
      - "8006:80"
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: ctracedemos_js_hello_1
      LOGFILE: "/var/log/js_gw.log"
      SERVICENAME: "js_gw"

  js_hello:
    build:
      context: ./js
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"

    image: ctrace-demo-js
    networks:
      - main
    ports:
      - "8007:80"
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      SERVICENAME: "js_hello"

volumes:
  ctrace-demo-logs:
