#!/usr/bin/env bash

sleep 15

/opt/flink/bin/flink run -m ${JOBMANAGER}:6123 -c com.nordstrom.mdt.StreamingJob /job/target/ctrace-zipkin-demo-converter-1.0-SNAPSHOT.jar --inputPath ${INPUT_PATH} --zipkinHost ${ZIPKIN_HOST}
